# Generated by Django 4.2.30 on 2026-07-12 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='transaction',
            new_name='core_transa_user_id_190a3b_idx',
            old_name='core_transa_user_id_6a8f0d_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='core_transa_user_id_04999f_idx',
            old_name='core_transa_user_id_8b2c1a_idx',
        ),
        migrations.AlterField(
            model_name='account',
            name='currency',
            field=models.CharField(default='COL', max_length=3, verbose_name='moneda'),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
    ]
