# Generated by Django 4.2.30 on 2026-07-13 00:27

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_core_transa_user_id_6a8f0d_idx_core_transa_user_id_190a3b_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountCreditCardDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_limit', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='cupo')),
                ('statement_day', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='día de corte')),
                ('payment_due_day', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='día límite de pago')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_card_details', to='core.account', verbose_name='cuenta')),
            ],
            options={
                'verbose_name': 'detalle de tarjeta de crédito',
                'verbose_name_plural': 'detalles de tarjeta de crédito',
            },
        ),
    ]
