# Generated by Django 4.2.30 on 2026-07-13 01:21

from django.db import migrations, models


def fix_col_to_cop(apps, schema_editor):
    Account = apps.get_model("core", "Account")
    Account.objects.filter(currency="COL").update(currency="COP")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_accountcreditcarddetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='currency',
            field=models.CharField(default='COP', max_length=10, verbose_name='moneda'),
        ),
        migrations.RunPython(fix_col_to_cop, migrations.RunPython.noop),
    ]
