# Generated by Django 4.2.30 on 2026-07-13 06:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_contact_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'grupo de contactos',
                'verbose_name_plural': 'grupos de contactos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ContactGroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha agregado')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='core.contact', verbose_name='contacto')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.contactgroup', verbose_name='grupo')),
            ],
            options={
                'verbose_name': 'integrante de grupo',
                'verbose_name_plural': 'integrantes de grupo',
                'unique_together': {('group', 'contact')},
            },
        ),
        migrations.AddField(
            model_name='contactgroup',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='groups', through='core.ContactGroupMembership', to='core.contact', verbose_name='integrantes'),
        ),
        migrations.AddField(
            model_name='contactgroup',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_groups', to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
        migrations.AlterUniqueTogether(
            name='contactgroup',
            unique_together={('user', 'name')},
        ),
    ]
