# Generated by Django 4.2.30 on 2026-07-13 20:39

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_contact_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='nombre')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('split_method', models.CharField(choices=[('equal', 'Igualitaria')], default='equal', max_length=20, verbose_name='método de división')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='shared_expense', to='core.transaction', verbose_name='transacción asociada')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'gasto compartido',
                'verbose_name_plural': 'gastos compartidos',
                'ordering': ['-transaction__date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SharedExpenseParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_owner', models.BooleanField(default=False, verbose_name='es el dueño')),
                ('is_payer', models.BooleanField(default=False, verbose_name='es quien pagó')),
                ('position', models.PositiveSmallIntegerField(default=0, help_text='Orden de aparición usado para el reparto de céntimos sobrantes.', verbose_name='posición')),
                ('amount_assigned', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='monto asignado')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='monto pagado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_expense_participations', to='core.contact')),
                ('shared_expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='core.sharedexpense')),
            ],
            options={
                'verbose_name': 'participante de gasto compartido',
                'verbose_name_plural': 'participantes de gasto compartido',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SharedExpensePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='monto')),
                ('date', models.DateField(verbose_name='fecha')),
                ('notes', models.TextField(blank=True, verbose_name='observación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.sharedexpenseparticipant')),
            ],
            options={
                'verbose_name': 'pago de gasto compartido',
                'verbose_name_plural': 'pagos de gastos compartidos',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='sharedexpenseparticipant',
            constraint=models.UniqueConstraint(fields=('shared_expense', 'contact'), name='shx_participant_unique_contact'),
        ),
        migrations.AddConstraint(
            model_name='sharedexpenseparticipant',
            constraint=models.UniqueConstraint(condition=models.Q(('is_owner', True)), fields=('shared_expense',), name='shx_participant_unique_owner'),
        ),
        migrations.AddConstraint(
            model_name='sharedexpenseparticipant',
            constraint=models.UniqueConstraint(condition=models.Q(('is_payer', True)), fields=('shared_expense',), name='shx_participant_unique_payer'),
        ),
    ]
