# Generated by Django 4.2.30 on 2026-07-13 21:26

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_shared_expense_module'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sharedexpense',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'gasto compartido', 'verbose_name_plural': 'gastos compartidos'},
        ),
        migrations.AddField(
            model_name='sharedexpense',
            name='account',
            field=models.ForeignKey(blank=True, help_text='Solo se completa cuando el dueño de la app es quien pagó.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_expenses', to='core.account', verbose_name='cuenta de origen'),
        ),
        migrations.AddField(
            model_name='sharedexpense',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_expenses', to='core.category'),
        ),
        migrations.AddField(
            model_name='sharedexpense',
            name='date',
            field=models.DateField(default='2026-01-01', verbose_name='fecha'),
        ),
        migrations.AddField(
            model_name='sharedexpense',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.01'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='monto total'),
        ),
        migrations.AddField(
            model_name='sharedexpensepayment',
            name='account',
            field=models.ForeignKey(blank=True, help_text='Solo se completa cuando el gasto original lo pagó el dueño de la app.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_expense_payments', to='core.account', verbose_name='cuenta donde se recibió'),
        ),
        migrations.AddField(
            model_name='sharedexpensepayment',
            name='transaction',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shared_expense_payment', to='core.transaction', verbose_name='transacción de ingreso asociada'),
        ),
        migrations.AlterField(
            model_name='sharedexpense',
            name='transaction',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shared_expense', to='core.transaction', verbose_name='transacción de gasto asociada'),
        ),
    ]
