# Generated by Django 4.2.30 on 2026-07-13 21:26

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_shared_expense_payment_transactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedexpense',
            name='date',
            field=models.DateField(verbose_name='fecha'),
        ),
        migrations.AlterField(
            model_name='sharedexpense',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='monto total'),
        ),
    ]
