# Generated by Django 4.2.30 on 2026-07-13 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_shared_expense_drop_temp_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedexpensepayment',
            name='account',
            field=models.ForeignKey(blank=True, help_text='Cuenta desde la que pagaste o en la que recibiste el dinero, si aplica.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_expense_payments', to='core.account', verbose_name='cuenta asociada'),
        ),
        migrations.AlterField(
            model_name='sharedexpensepayment',
            name='transaction',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shared_expense_payment', to='core.transaction', verbose_name='transacción asociada'),
        ),
    ]
