# Generated by Django 4.2.30 on 2026-07-13 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_sharedexpensepayment_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedexpensepayment',
            name='account',
            field=models.ForeignKey(blank=True, help_text='Cuenta desde donde pagaste o donde recibiste el dinero, si aplica.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_expense_payments', to='core.account', verbose_name='cuenta asociada'),
        ),
    ]
